### ISSUE TITLE
Getters & Setters broke after the revert

### ISSUE THREAD

**Issue by GeopJr** [hugopl/gi-crystal#3]
Hi, I was working on libadwaita bindings and was using gi-crystal of 5a3ca155ac54be951b07d1ffb32909d69d9bac98.
After updating to b6965354333bf24ee6fbd6e91c0147a1fba7614c getters and setters of Adw broke.

Eg. in `Adw::ApplicationWindow`, the following got added:

```crystal
def content=(value : Widget?) : Widget?
      unsafe_value = value

      LibGObject.g_object_set(self, "content", unsafe_value, Pointer(Void).null)
      value
    end

    def content : Widget?
      # Returns: None

      value = uninitialized Pointer(Void)
      LibGObject.g_object_get(self, "content", pointerof(value), Pointer(Void).null)
      Gtk::Widget.new(value, GICrystal::Transfer::None) unless value.null?
    end
```

but when running one of the examples (or specs) I get the following error:
```bash
In src/auto/adw-1/application_window.cr:360:26

 360 | def content=(value : Widget?) : Widget?
                            ^-----
Error: undefined constant Widget
```

In this case/libadwaita's chaning all instances of `Widget` to `Gtk::Widget` fixes it. It's not really an issue for [libadwaita.cr](https://github.com/GeopJr/libadwaita.cr) since gi-crystal is locked to 5a3ca155ac54be951b07d1ffb32909d69d9bac98 and the bindings are not being generated on demand, but thought I should create this issue just in case.

**Comment by GeopJr** [comment]
Actually, I should have taken a better look, it seems that now there are 2 of them?
![image](https://user-images.githubusercontent.com/18014039/137556029-3ac2cbe1-7c36-4082-8401-e088e00ac582.png)

**Comment by GeopJr** [comment]
Makes sense, thanks! libadwaita.cr will stay locked on 5a3ca155ac54be951b07d1ffb32909d69d9bac98 for now then 😅

**Comment by hugopl** [comment]
Fixed :-)
