### ISSUE TITLE
Inheriting from a non-user class which inherits from a class implementing interfaces re-includes that interface

### ISSUE THREAD

**Issue by BlobCodes** [hugopl/gi-crystal#31]
I recently wanted to create a widget inheriting from [`Adw::Bin`](https://libadwaita.geopjr.dev/docs/Adw/Bin.html). It itself is a subclass of [`Gtk::Widget`](https://libadwaita.geopjr.dev/docs/Gtk/Widget.html), which implements the three interfaces: [`Gtk::Accessible`](https://libadwaita.geopjr.dev/docs/Gtk/Accessible.html), [`Gtk::Buildable`](https://libadwaita.geopjr.dev/docs/Gtk/Buildable.html) and [`Gtk::ConstraintTarget`](https://libadwaita.geopjr.dev/docs/Gtk/ConstraintTarget.html).

When subclassing it, the following is printed to `STDOUT`:
```
(crystal-run-mangaba.tmp:37321): GLib-GObject-WARNING **: 16:07:17.256: cannot add interface type 'GtkConstraintTarget' to type 'Mangaba-UI-Description', since type 'Mangaba-UI-Description' already conforms to interface

(crystal-run-mangaba.tmp:37321): GLib-GObject-WARNING **: 16:07:17.256: cannot add interface type 'GtkBuildable' to type 'Mangaba-UI-Description', since type 'Mangaba-UI-Description' already conforms to interface

(crystal-run-mangaba.tmp:37321): GLib-GObject-WARNING **: 16:07:17.256: cannot add interface type 'GtkAccessible' to type 'Mangaba-UI-Description', since type 'Mangaba-UI-Description' already conforms to interface

(crystal-run-mangaba.tmp:37321): GLib-GObject-WARNING **: 16:07:17.256: cannot add interface type 'GtkConstraintTarget' to type 'Mangaba-UI-Description', since type 'Mangaba-UI-Description' already conforms to interface

(crystal-run-mangaba.tmp:37321): GLib-GObject-WARNING **: 16:07:17.256: cannot add interface type 'GtkBuildable' to type 'Mangaba-UI-Description', since type 'Mangaba-UI-Description' already conforms to interface

(crystal-run-mangaba.tmp:37321): GLib-GObject-WARNING **: 16:07:17.256: cannot add interface type 'GtkAccessible' to type 'Mangaba-UI-Description', since type 'Mangaba-UI-Description' already conforms to interface
```

As you can see, each of these three interfaces gets implemented three times.

We can either refactor the interface inheriting code or create a class variable (ex. `@@_implemented_gtk_buildable`) which we use to only implement it once.

**Comment by hugopl** [comment]
I moved the interface code to a branch `feature-interface`, same hash as master, then I force pushed master to before the interfaces being added (just for being lazzy to do 2 reverts).

So while interfaces/vfunc implementation isn't regression-free we can have a clean master branch, then later merge it into master.
