### ISSUE TITLE
Return types from vfuncs are not converted

### ISSUE THREAD

**Issue by BlobCodes** [hugopl/gi-crystal#34]
(yes this is my fault)

Currently, return values from vfuncs implemented by GObject subclasses are not converted.
For example, if I want to implement the vfunc `get_request_mode`, I would normally assume I have to return a `Gtk::SizeRequestMode`. However, the current implementation wants me to return a `UInt32`.

I think we can copy the code used for conversion to c-types from the signal implementation (which is what I did for the vfunc parameters as well).

**Comment by hugopl** [comment]
BTW, this isn't your fault **at all**, the vfuncs implementation is great and it doesn't need to be 100% functional and bug free from day 0.
