### ISSUE TITLE
[question] how to Include other modules like `GLib`

### ISSUE THREAD

**Issue by aeldemery** [hugopl/gi-crystal#54]
how to include other modules like `Glib` in the project.

thanks

**Comment by aeldemery** [comment]
Ok. Find out that its grouped under `GLib.` not `GLib::` which is perhaps inconsistent.

**Comment by hugopl** [comment]
`::` or `.` depends if it’s a constant or a module function.

But if I got your question correctly you are talking about `GICrystal.require`
