### ISSUE TITLE
Constant treated as type

### ISSUE THREAD

**Issue by GeopJr** [hugopl/gi-crystal#6]
I came across the following error while calling [`Gio::Resource#enumerate_children`](https://libadwaita.geopjr.dev/docs/Gio/Resource.html#new_from_data%28data%3AGLib%3A%3ABytes%29%3Aself-class-method):

```bash
In lib/gi-crystal/src/auto/gio-2.0/resource.cr:201:60

 201 | def enumerate_children(path : ::String, lookup_flags : Gio::ResourceLookupFlags) : Enumerable(::String)
                                                              ^-----------------------
Error: Gio::ResourceLookupFlags is not a type, it's a constant
```

From a quick look, it happens on [src/generator/helpers.cr#L162-L165](https://github.com/hugopl/gi-crystal/blob/master/src/generator/helpers.cr#L162-L165) but I'm unsure how to distinguish interface from constant (if that's even what I'm supposed to do).

Corrent type should be [UInt32](https://github.com/GeopJr/libadwaita.cr/blob/a6d353530a72c869e1735ecb8cc1c02837fcaf32/src/auto/gio-2.0/lib_gio.cr#L36) (or should Gio::ResourceLookupFlags be an enum with just one item? (https://docs.gtk.org/gio/flags.ResourceLookupFlags.html))

(I don't use this or the others that are affected (#info, #lookup_data, #open_stream) so priority is low 😅)

**Comment by hugopl** [comment]
The issue is here https://github.com/hugopl/gi-crystal/blob/master/ecr/module.ecr#L46

Now I need to remember why this condition exists, hehehe, and create a test case in libtest.
